---
# tasks file for node_invite
- name: Copy the join command to server location # копируем файл с нашей командой для присоединения ноды на сервер, меняем расширение и добавляем права на исполнение
  become: yes
  copy:
    src: join-command
    dest: /tmp/join-command.sh
    owner: ubuntu
    group: ubuntu
    mode: 0777
  
#  synchronize:
#    mode: pull
#    src: /home/ubuntu/join-command
#    dest: /tmp/join-command.sh
    
#  copy:
#   src: join-command
#   dest: /tmp/join-command.sh
#   mode: 0777

- name: Join the node to cluster # запускаем наш файл
  command: sh /tmp/join-command.sh
