---
- hosts: kube_master
  become: yes
  tasks:
    - name: Installing necessary packages
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Adding GPG Kubernetes keys
      apt_key:
        url: https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        state: present
    
    - name: Adding repository Kubernetes
      apt_repository:
        repo: deb https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list
        state: present

    - name: Installing Kubelet, Kubeadm è Kubectl
      apt:
        name: 
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: yes

    - name: Disable swap
      command: swapoff -a

- hosts: kube_nodes
  become: yes
  tasks:
    - name: Installing necessary packages
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Adding GPG Kubernetes keys
      apt_key:
        url: https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        state: present
    
    - name: Adding repository Kubernetes
      apt_repository:
        repo: deb https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list
        state: present

    - name: Installing Kubelet, Kubeadm è Kubectl
      apt:
        name: 
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: yes

    - name: Disable swap
      command: swapoff -a