---
   - hosts: 127.0.0.1
     become: yes
     tasks:
       - name: Update apt repository
         apt:
           update_cache: yes

       - name: Install Docker
         apt:
           name: docker.io
           state: present

       - name: Install Docker Compose
         apt:
           name: python3-pip
           state: present

       - name: Install pip for Docker Compose
         pip:
           name: docker-compose

       - name: Install GitLab Runner
         shell: |
           https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh | sudo bash
           apt install gitlab-runner -y

       - name: Setup SSH keys
         authorized_key:
           user: ubuntu
           state: present
           key: "{{ lookup('file', 'path/to/your/public_key.pub') }}"
            mode: '0644'
