---
   - hosts: 127.0.0.1
     become: yes
     tasks:
       - name: Update apt repository
         apt:
           update_cache: yes

       - name: Install Docker
         apt:
           name: docker.io
           state: present

       - name: Install Docker Compose
         apt:
           name: python3-pip
           state: present

       - name: Install pip for Docker Compose
         pip:
           name: docker-compose

       - name: Install GitLab Runner
         shell: |
           https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh | sudo bash
           apt install gitlab-runner -y

       - name: Copy SSH key
         copy:
           src: ~/.ssh/yandex_public_key.pub
           dest: ~/.ssh/authorized_keys
           mode: '0644'

       - name: Setup SSH keys
         authorized_key:
           user: ubuntu
           state: present
           key: ~/.ssh/yandex_public_key.pub
